name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Match your Lambda runtime

      - name: Install dependencies
        run: npm install

      - name: Download RDS global bundle
        run: |
          mkdir -p certs
          wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O certs/global-bundle.pem

      - name: Create Lambda zip
        run: |
          zip -r lambda.zip . -x ".git/*" "tests/*" "*.github/*" "*.gitignore"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name node-docdb-app \
            --zip-file fileb://lambda.zip
