name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip source code
        run: zip -r lambda.zip .

      - name: Upload to Lambda
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
   
      
      - name: Upload to Lambda
        run: |
          aws lambda update-function-code \
            --function-name node-docdb-app \
            --zip-file fileb://lambda.zip
